name: ChatGPT API Call

on:
  push:
    branches:
      - main

jobs:
  call-openai-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run OpenAI API call script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        chmod +x ./call_openai.sh
        ./call_openai.sh $OPENAI_API_KEY

    - name: Upload response
      uses: actions/upload-artifact@v4
      with:
        name: api-response
        path: response.json
